import '../globals.css';
import NavbarComponent from './components/navbar.component';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        <NavbarComponent />
        {children}
      </body>
    </html>
  )
}
